controls:
  /huggingface/model:
    type: TextControl
    required: true
  /huggingface/token:
    type: TextControl
    secret: true
  # Use mirror to mimic yaml anchor in base Helm chart
  /ui/appSettings/hf_model_name:
    type: MirrorControl
    path: /huggingface/model
    visuallyHidden: true

sortOrder:
  - /huggingface/model
  - /huggingface/token
  - /ui/appSettings/hf_model_instruction
  - /ui/appSettings/page_title
  - /ui/appSettings/llm_temperature
