controls:
  /huggingface/model:
    type: TextControl
    required: true
  /huggingface/token:
    type: TextControl
    secret: true
  /ui/appSettings/hf_model_instruction:
    type: TextControl
  /ui/appSettings/page_title:
    type: TextControl
  /ui/appSettings/llm_max_tokens:
    type: NumberControl
  /ui/appSettings/llm_temperature:
    type: NumberControl
  /ui/appSettings/llm_top_p:
    type: NumberControl
  /ui/appSettings/llm_frequency_penalty:
    type: NumberControl
  /ui/appSettings/llm_presence_penalty:
    type: NumberControl
  # Use mirror to mimic yaml anchor in base Helm chart
  /ui/appSettings/model_name:
    type: MirrorControl
    path: /huggingface/model
    visuallyHidden: true