controls:
  /huggingface/model:
    type: TextControl
    placeholder: mistralai/Mistral-7B-Instruct-v0.2
    required: true
  /huggingface/token:
    type: TextControl
    secret: true
  /ui/appSettings/model_instruction:
    type: TextControl
    placeholder: "You are a helpful AI assistant. Please respond appropriately"
  /ui/appSettings/page_title:
    type: TextControl
    placeholder: "Large Language Model"
  /ui/appSettings/llm_max_tokens:
    type: NumberControl
  /ui/appSettings/llm_temperature:
    type: NumberControl
  /ui/appSettings/llm_top_p:
    type: NumberControl
  /ui/appSettings/llm_frequency_penalty:
    type: NumberControl
  /ui/appSettings/llm_presence_penalty:
    type: NumberControl
  # Use mirror to mimic yaml anchor in base Helm chart
  /ui/appSettings/model_name:
    type: MirrorControl
    path: /huggingface/model
    visuallyHidden: true