---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "flux-image-gen.fullname" . }}-ui
  labels:
    {{- include "flux-image-gen.labels" $ | nindent 4 }}
    {{- include "flux-image-gen.uiLabels" . | nindent 4 }}
spec:
  type: {{ .Values.ui.service.type }}
  ports:
    - port: {{ .Values.ui.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "flux-image-gen.selectorLabels" . | nindent 4 }}
    {{- include "flux-image-gen.uiLabels" . | nindent 4 }}
