---

version: 2

updates:
  # Automatically propose PRs for out-of-date GitHub actions
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      # Check for new versions weekly
      interval: weekly
    # Update all actions in a single PR
    groups:
      github-actions:
        patterns: ["*"]

# TODO: Add web app python dependencies
