{{- range $model := .Values.models }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-%s-api" (include "flux-image-gen.fullname" $) $model }}
  labels:
    {{- include "flux-image-gen.labels" $ | nindent 4 }}
    {{- include "flux-image-gen.modelLabels" . | nindent 4 }}
spec:
  type: {{ $.Values.api.service.type }}
  ports:
    - port: {{ $.Values.api.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "flux-image-gen.selectorLabels" $ | nindent 4 }}
    {{- include "flux-image-gen.modelLabels" . | nindent 4 }}
{{- end -}}
