{{- if and .Values.api.enabled .Values.api.service.zenith.enabled -}}
apiVersion: zenith.stackhpc.com/v1alpha1
kind: Client
metadata:
  name: {{ .Release.Name }}-api
  labels:
    {{- include "azimuth-llm.labels" . | nindent 4 }}
spec:
  reservationName: {{ .Release.Name }}-api
  upstream:
    serviceName: {{ .Release.Name }}-api
  auth:
    skip: {{ .Values.api.service.zenith.skipAuth }}
{{- end -}}
