backend_url: http://128.232.226.230
hf_model_name: tiiuae/falcon-7b

hf_model_instruction: You are a helpful and cheerful AI assistant. Please respond appropriately.

# UI theming tweaks
# theme_title_colour: white
# theme_background_colour: "#00376c"
# theme_params:
#   primary_hue: blue

# llm_max_tokens:
# llm_temperature:
# llm_top_p:
# llm_frequency_penalty:
# llm_presence_penalty:
