azimuth-llm:
  api:
    enabled: false
  ui:
    service:
      zenith:
        enabled: false
    appSettings:
      # Verify that we can set non-standard LLM params
      llm_params:
        max_tokens: 101
        temperature: 0.1
        top_p: 0.15
        top_k: 1
        presence_penalty: 0.9
        frequency_penalty: 1
