apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.api.service.name }}
  labels:
    {{- include "azimuth-llm.api-selectorLabels" . | nindent 4 }}
spec:
  ports:
  - name: api
    port: 80
    protocol: TCP
    targetPort: api
  type: {{ .Values.api.service.type }}
  selector:
    {{- include "azimuth-llm.api-selectorLabels" . | nindent 4 }}
