{{- if .Values.ui.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-web-app
  labels:
    {{- include "azimuth-llm.labels" . | nindent 4 }}
data:
  overrides.yml: |
    {{- $_ := set .Values.ui.appSettings "backend_url" (printf "http://%s-api.%s.svc" .Release.Name .Release.Namespace) }}
    {{- .Values.ui.appSettings | toYaml | nindent 4 }}
{{- end -}}
