{{- if .Values.ui.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-ui
  labels:
    {{- include "azimuth-llm.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "azimuth-llm.ui-selectorLabels" . | nindent 6 }}
  strategy:
    {{- .Values.ui.updateStrategy | toYaml | nindent 4 }}
  template:
    metadata:
      labels:
        {{- include "azimuth-llm.ui-selectorLabels" . | nindent 8 }}
      # Restart deployment when settings config map changes
      # https://helm.sh/docs/howto/charts_tips_and_tricks/#automatically-roll-deployments
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/ui/app-config-map.yml") . | sha256sum }}
    spec:
      containers:
      - name: {{ .Release.Name }}-ui
        {{- with .Values.ui.image }}
        image: {{ printf "%s:%s" .repository .version }}
        {{- if .imagePullPolicy }}
        imagePullPolicy: {{ .imagePullPolicy }}
        {{- end -}}
        {{- end }}
        ports:
        - name: ui
          containerPort: 7860
        volumeMounts:
        - name: app
          mountPath: /etc/web-app
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        tty: true # Make stdout from python visible in k8s logs
        readinessProbe:
          tcpSocket:
            port: 7860
          periodSeconds: 5
      volumes:
        - name: app
          configMap:
            name: {{ .Release.Name }}-web-app
{{- end -}}
