{{- if and .Values.ui.enabled .Values.ingress.ui.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  {{ if .Values.ingress.ui.annotations -}}
  annotations:
    {{- .Values.ingress.ui.annotations | toYaml | nindent 4 }}
  {{ end -}}
  name: {{ default (printf "%s-ui" .Release.Name) .Values.ingress.ui.name }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
  - http:
      paths:
      - path: {{ .Values.ingress.ui.path }}
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-ui
            port:
              # Must match Service resource
              number: 80
    {{ if .Values.ingress.host -}}
    host: {{ .Values.ingress.host | quote }}
    {{- end -}}
  {{- if .Values.ingress.tls }}
  tls:
  - hosts:
    - {{ (required "ingress.host is required when ingress.tls is true" .Values.ingress.host) | quote }}
    secretName: {{ .Release.Name }}-ui-tls
  {{- end -}}
{{- end -}}
