controls:
  /azimuth-llm/huggingface/model:
    type: TextControl
    required: true
  /azimuth-llm/huggingface/token:
    type: TextControl
    secret: true
  # Use mirror to mimic yaml anchor in base Helm chart
  /azimuth-llm/ui/appSettings/hf_model_name:
    type: MirrorControl
    path: /azimuth-llm/huggingface/model
    visuallyHidden: true

sortOrder:
  - /huggingface/model
  - /huggingface/token
  - /ui/appSettings/hf_model_instruction
  - /ui/appSettings/page_title
  - /api/image/version
  - /ui/appSettings/llm_temperature
  - /ui/appSettings/llm_max_tokens
  - /ui/appSettings/llm_frequency_penalty
  - /ui/appSettings/llm_presence_penalty
  - /ui/appSettings/llm_top_p
  - /ui/appSettings/llm_top_k
  - /api/modelMaxContextLength
