controls:
  /azimuth-llm/huggingface/model:
    type: TextControl
    required: true
  /azimuth-llm/huggingface/token:
    type: TextControl
    secret: true
  # Use mirror to mimic yaml anchor in base Helm chart
  /azimuth-llm/ui/appSettings/model_name:
    type: MirrorControl
    path: /azimuth-llm/huggingface/model
    visuallyHidden: true

sortOrder:
  - /huggingface/model
  - /huggingface/token
  - /api/image/version
  - /ui/appSettings/llm_params/temperature
  - /ui/appSettings/llm_params/max_tokens
  - /ui/appSettings/llm_params/frequency_penalty
  - /ui/appSettings/llm_params/presence_penalty
  - /ui/appSettings/llm_params/top_p
  - /ui/appSettings/llm_params/top_k
