azimuth-llm:
  huggingface:
    model: &model-name Qwen/Qwen2-VL-7B-Instruct
  ui:
    image:
      repository: ghcr.io/stackhpc/azimuth-llm-image-analysis-ui
    service:
      zenith:
        enabled: true
        label: Image Analysis Interface
    appSettings:
      model_name: *model-name
