apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-web-app
  labels:
    {{- include "azimuth-llm.labels" . | nindent 4 }}
data:
{{ (.Files.Glob "web-app/*").AsConfig | nindent 2 }}
  settings.py: |
    {{- .Values.ui.appSettings | toYaml | nindent 4 }}
