apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-web-app
  labels:
    {{- include "azimuth-llm.labels" . | nindent 4 }}
data:
{{ (.Files.Glob "web-app-utils/*").AsConfig | nindent 2 }}