apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-ui
  labels:
    {{- include "azimuth-llm.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels: 
      {{- include "azimuth-llm.ui-selectorLabels" . | nindent 6 }}
  strategy:
    {{- .Values.ui.updateStrategy | toYaml | nindent 4 }}
  template:
    metadata:
      labels:
        {{- include "azimuth-llm.ui-selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Release.Name }}-ui
        image: {{ printf "%s:%s" .Values.ui.image.repository .Values.ui.image.version }}
        ports:
        - name: ui
          containerPort: 7680
        volumeMounts:
        - name: app
          mountPath: /etc/web-app
        command: 
        - python
        args:
        - /etc/web-app/app.py
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        tty: true # Make stdout from python visible in k8s logs
        readinessProbe:
          tcpSocket:
            port: 7680
          periodSeconds: 5
      volumes:
        - name: app
          configMap:
            name: {{ .Release.Name }}-web-app