{{- if .Values.api.service.zenith.enabled -}}
apiVersion: zenith.stackhpc.com/v1alpha1
kind: Reservation
metadata:
  name: {{ .Release.Name }}-ui
  labels:
    {{- include "azimuth-llm.labels" . | nindent 4 }}
spec:
  credentialSecretName: {{ .Release.Name }}-ui-zenith-credential
{{- end -}}