apiVersion: zenith.stackhpc.com/v1alpha1
kind: Client
metadata:
  name: azimuth-llm-ui
  labels:
    {{- include "azimuth-llm.labels" . | nindent 4 }}
spec:
  reservationName: azimuth-llm-ui
  upstream:
    serviceName: gradio-app
  auth:
    skip: true