{{- if .Values.ui.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.ui.service.name }}
  labels:
    {{- include "azimuth-llm.labels" . | nindent 4 }}
spec:
  ports:
  - name: ui
    port: 80
    protocol: TCP
    targetPort: ui
  type: {{ .Values.ui.service.type }}
  selector:
    {{- include "azimuth-llm.ui-selectorLabels" . | nindent 4 }}
{{- end -}}
