apiVersion: v1
kind: Service
metadata:
  name: text-generation-inference
  labels:
    {{- include "azimuth-llm.labels" . | nindent 4 }}
spec:
  ports:
  - name: api
    port: 80
    protocol: TCP
    targetPort: api
  selector:
    # azimuth-llm: api
    {{- include "azimuth-llm.api-selectorLabels" . | nindent 4 }}