# Adapted from https://github.com/stackhpc/azimuth/blob/master/.github/workflows/build-push-artifacts.yaml
name: Publish artifacts

on:
  # Publish artifacts on every push to master and every tag
  push:
    branches:
      - main
    tags:
      - "*"

jobs:
  publish_images:
    uses: ./.github/workflows/build-push-images.yml
    with:
      ref: ${{ github.ref }}
    secrets: inherit

  publish_charts:
    needs: [publish_images]
    uses: ./.github/workflows/build-push-charts.yml
    with:
      ref: ${{ github.ref }}
    secrets: inherit
