# Adapted from https://github.com/stackhpc/azimuth/blob/master/.github/workflows/build-push-artifacts.yaml
name: Publish container images

on:
  workflow_call:
    inputs:
      ref:
        type: string
        description: The ref to build.
        required: true

jobs:
  build_push_images:
    name: Build and push images
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - component: chat
          - component: image-analysis
    permissions:
      contents: read
      id-token: write         # needed for signing the images with GitHub OIDC Token
      packages: write         # required for pushing container images
      security-events: write  # required for pushing SARIF files
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get SemVer version for current commit
        id: semver
        uses: azimuth-cloud/github-actions/semver@master

      - name: Calculate metadata for image
        id: image-meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/stackhpc/azimuth-llm-${{ matrix.component }}-ui
          # Produce the branch name or tag and the SHA as tags
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=raw,value=${{ steps.semver.outputs.short-sha }}

      - name: Build and push image
        uses: azimuth-cloud/github-actions/docker-multiarch-build-push@master
        with:
          cache-key: ${{ matrix.component }}
          context: ./web-apps/
          file: ./web-apps/${{ matrix.component }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.image-meta.outputs.tags }}
          labels: ${{ steps.image-meta.outputs.labels }}
