# Based on https://github.com/azimuth-cloud/azimuth/blob/master/.github/workflows/test-pr.yaml
name: Test pull request

on:
  pull_request:
    types:
      - opened
      - synchronize
      - ready_for_review
      - reopened
    branches:
      - main

# Use the head ref for workflow concurrency, with cancellation
# This should mean that any previous workflows for a PR get cancelled when a new commit is pushed
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  # This job exists so that PRs from outside the main repo are rejected
  fail_on_remote:
    runs-on: ubuntu-latest
    steps:
      - name: PR must be from a branch in the stackhpc/azimuth-llm repo
        run: exit ${{ github.event.pull_request.head.repo.full_name == 'stackhpc/azimuth-llm' && '0' || '1' }}

  publish_images:
    needs: [fail_on_remote]
    uses: ./.github/workflows/build-push-images.yml
    with:
      ref: ${{ github.sha }}
    secrets: inherit

  publish_charts:
    needs: [fail_on_remote]
    uses: ./.github/workflows/build-push-charts.yml
    with:
      ref: ${{ github.sha }}
    secrets: inherit
    permissions:
      # Explicit permissions are required for
      # PRs created by dependabot user
      contents: write

  chart_validation:
    needs: [publish_images]
    runs-on: ubuntu-latest
    env:
      CLUSTER_NAME: chart-testing
      RELEASE_NAME: ci-test
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v5
        with:
          ref: ${{ github.sha }}

      - name: Reconfigure docker storage
        # GitHub runners have an extra 75G disk at /mnt
        # so we use this to avoid hitting capacity issues
        # with kind cluster + vLLM container images
        run: |
          sudo bash -c 'cat > /etc/docker/daemon.json' << EOF
          {
            "data-root": "/mnt/docker-data"
          }
          EOF
          sudo systemctl restart docker

      - name: Run Gradio app tests
        run: |
          echo "Installing ollama..."
          curl -fsSL https://ollama.com/install.sh | sh

          # Give ollama systemd unit time to start
          sleep 5

          MODEL=smollm2:135m
          echo "Pulling model $MODEL..."
          ollama pull $MODEL

          echo "Running Gradio test script"
          ./test-images.sh $(git rev-parse --short ${{ github.sha }})
        working-directory: web-apps

      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: Run base chart templating with default values
        run: helm template ci-test charts/azimuth-llm

      - name: Set up chart testing
        uses: helm/chart-testing-action@v2

      - name: Run chart linting
        run: ct lint --config ct.yaml

      - name: Create Kind Cluster
        uses: helm/kind-action@v1
        with:
          cluster_name: ${{ env.CLUSTER_NAME }}

      # NOTE(scott): Since the local Chart.yaml uses "appVersion: latest" and this
      # only gets overwritten to the correct commit SHA during Helm chart build,
      # we need to pull these published images and load them into the kind cluster
      # with the tag correct tag.
      - name: Load tagged container images into kind cluster
        run: ./kind-images.sh $(git rev-parse --short ${{ github.sha }}) ${{ env.CLUSTER_NAME }}
        working-directory: web-apps

      # https://github.com/helm/charts/blob/master/test/README.md#providing-custom-test-values
      # Each chart/ci/*-values.yaml file will be treated as a separate test case with it's
      # own helm install/test process.
      - name: Run chart install and test
        run: ct install --config ct.yaml
